[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckEnabled = true
healthcheckPath = "/simple-health"
healthcheckTimeout = 120
