"""Add premium background replacement system

Revision ID: 976ddc7b1fee
Revises: 
Create Date: 2025-07-10 10:05:13.940475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '976ddc7b1fee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('module', sa.String(length=64), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_id'), 'logs', ['id'], unique=False)
    op.create_table('premium_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_key', sa.String(length=64), nullable=False),
    sa.Column('feature_name', sa.String(length=128), nullable=False),
    sa.Column('feature_type', sa.Enum('BACKGROUND_REPLACEMENT', 'VIDEO_EDITING', 'AI_IMAGE_GENERATION', 'BULK_PROCESSING', name='featuretype'), nullable=False),
    sa.Column('min_tier', sa.Enum('FREE', 'STARTER', 'PRO', 'ENTERPRISE', name='subscriptiontier'), nullable=False),
    sa.Column('trial_access', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature_key')
    )
    op.create_index(op.f('ix_premium_features_id'), 'premium_features', ['id'], unique=False)
    op.create_table('uploaded_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_images_id'), 'uploaded_images', ['id'], unique=False)
    op.create_table('user_backgrounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('cloudinary_url', sa.String(length=512), nullable=False),
    sa.Column('background_type', sa.Enum('UPLOAD', 'AI_GENERATED', 'STOCK', name='backgroundtype'), nullable=False),
    sa.Column('ai_prompt', sa.Text(), nullable=True),
    sa.Column('stock_source', sa.String(length=64), nullable=True),
    sa.Column('stock_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_backgrounds_id'), 'user_backgrounds', ['id'], unique=False)
    op.create_table('user_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tier', sa.Enum('FREE', 'STARTER', 'PRO', 'ENTERPRISE', name='subscriptiontier'), nullable=True),
    sa.Column('trial_started_at', sa.DateTime(), nullable=True),
    sa.Column('trial_expires_at', sa.DateTime(), nullable=True),
    sa.Column('premium_expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_subscriptions_id'), 'user_subscriptions', ['id'], unique=False)
    op.create_table('user_feature_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('feature_key', sa.String(length=64), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['user_subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_feature_usage_id'), 'user_feature_usage', ['id'], unique=False)
    op.create_table('background_replacement_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('background_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=True),
    sa.Column('heygen_job_id', sa.String(length=128), nullable=True),
    sa.Column('transparent_video_url', sa.String(length=512), nullable=True),
    sa.Column('output_video_url', sa.String(length=512), nullable=True),
    sa.Column('output_thumbnail_url', sa.String(length=512), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['background_id'], ['user_backgrounds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index(op.f('ix_background_replacement_jobs_id'), 'background_replacement_jobs', ['id'], unique=False)
    op.drop_table('account_deletion_log')
    op.drop_table('settings')
    op.drop_table('templates')
    op.drop_index('idx_user_avatars_user_id', table_name='user_avatars')
    op.drop_table('user_avatars')
    op.drop_index('idx_api_logs_user_id', table_name='api_logs')
    op.drop_table('api_logs')
    op.drop_table('backgrounds')
    op.drop_table('gdpr_consent_log')
    op.add_column('avatars', sa.Column('url', sa.String(length=256), nullable=False))
    op.add_column('avatars', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('avatars', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.drop_constraint('avatars_avatar_id_key', 'avatars', type_='unique')
    op.create_index(op.f('ix_avatars_id'), 'avatars', ['id'], unique=False)
    op.create_foreign_key(None, 'avatars', 'users', ['user_id'], ['id'])
    op.drop_column('avatars', 'preview_video_url')
    op.drop_column('avatars', 'is_active')
    op.drop_column('avatars', 'avatar_id')
    op.drop_column('avatars', 'image_url')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'gdpr_consent_version')
    op.drop_column('users', 'gdpr_consent_timestamp')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'last_video_created')
    op.drop_column('users', 'gdpr_consent_given')
    op.drop_column('users', 'heygen_voice_id')
    op.add_column('videos', sa.Column('url', sa.String(length=256), nullable=False))
    op.alter_column('videos', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=32),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('videos', 'avatar_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index('idx_videos_status', table_name='videos')
    op.drop_index('idx_videos_user_id', table_name='videos')
    op.create_index(op.f('ix_videos_id'), 'videos', ['id'], unique=False)
    op.drop_constraint('videos_user_id_fkey', 'videos', type_='foreignkey')
    op.create_foreign_key(None, 'videos', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'videos', 'avatars', ['avatar_id'], ['id'])
    op.drop_column('videos', 'template_id')
    op.drop_column('videos', 'aspect_ratio')
    op.drop_column('videos', 'background_config')
    op.drop_column('videos', 'format')
    op.drop_column('videos', 'quality')
    op.drop_column('videos', 'script_content')
    op.drop_column('videos', 'duration')
    op.drop_column('videos', 'description')
    op.drop_column('videos', 'voice_id')
    op.drop_column('videos', 'title')
    op.drop_column('videos', 'completed_at')
    op.drop_column('videos', 'heygen_video_id')
    op.drop_column('videos', 'thumbnail_url')
    op.drop_column('videos', 'video_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('video_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('thumbnail_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('heygen_video_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('voice_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('script_content', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('quality', sa.VARCHAR(length=10), server_default=sa.text("'720p'::character varying"), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('format', sa.VARCHAR(length=10), server_default=sa.text("'16:9'::character varying"), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('background_config', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('aspect_ratio', sa.VARCHAR(length=10), server_default=sa.text("'16:9'::character varying"), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('template_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.create_foreign_key('videos_user_id_fkey', 'videos', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_videos_id'), table_name='videos')
    op.create_index('idx_videos_user_id', 'videos', ['user_id'], unique=False)
    op.create_index('idx_videos_status', 'videos', ['status'], unique=False)
    op.alter_column('videos', 'avatar_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('videos', 'status',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_column('videos', 'url')
    op.add_column('users', sa.Column('heygen_voice_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('gdpr_consent_given', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_video_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('gdpr_consent_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('gdpr_consent_version', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.add_column('avatars', sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('avatars', sa.Column('avatar_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('avatars', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('avatars', sa.Column('preview_video_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'avatars', type_='foreignkey')
    op.drop_index(op.f('ix_avatars_id'), table_name='avatars')
    op.create_unique_constraint('avatars_avatar_id_key', 'avatars', ['avatar_id'])
    op.alter_column('avatars', 'name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('avatars', 'user_id')
    op.drop_column('avatars', 'url')
    op.create_table('gdpr_consent_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('consent_given', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('consent_version', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('consent_timestamp', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='gdpr_consent_log_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='gdpr_consent_log_pkey')
    )
    op.create_table('backgrounds',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='backgrounds_pkey')
    )
    op.create_table('api_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('endpoint', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('method', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('response_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='api_logs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='api_logs_pkey')
    )
    op.create_index('idx_api_logs_user_id', 'api_logs', ['user_id'], unique=False)
    op.create_table('user_avatars',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avatar_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('avatar_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('avatar_image_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('preview_video_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_default', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_custom', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_avatars_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_avatars_pkey')
    )
    op.create_index('idx_user_avatars_user_id', 'user_avatars', ['user_id'], unique=False)
    op.create_table('templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('config', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='templates_pkey')
    )
    op.create_table('settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='settings_pkey'),
    sa.UniqueConstraint('key', name='settings_key_key')
    )
    op.create_table('account_deletion_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('deleted_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('admin_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deletion_timestamp', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('deletion_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='account_deletion_log_pkey')
    )
    op.drop_index(op.f('ix_background_replacement_jobs_id'), table_name='background_replacement_jobs')
    op.drop_table('background_replacement_jobs')
    op.drop_index(op.f('ix_user_feature_usage_id'), table_name='user_feature_usage')
    op.drop_table('user_feature_usage')
    op.drop_index(op.f('ix_user_subscriptions_id'), table_name='user_subscriptions')
    op.drop_table('user_subscriptions')
    op.drop_index(op.f('ix_user_backgrounds_id'), table_name='user_backgrounds')
    op.drop_table('user_backgrounds')
    op.drop_index(op.f('ix_uploaded_images_id'), table_name='uploaded_images')
    op.drop_table('uploaded_images')
    op.drop_index(op.f('ix_premium_features_id'), table_name='premium_features')
    op.drop_table('premium_features')
    op.drop_index(op.f('ix_logs_id'), table_name='logs')
    op.drop_table('logs')
    # ### end Alembic commands ###
